### ISSUE TITLE
Remove non-standard attributes added by CloudStreams

### ISSUE THREAD

**Issue by bvandewe** [neuroglia-io/cloud-streams#63]
**Describe the bug**
All events streamed by CS' broker have two additional non-standard attributes (`$traceId` and `$spanId`) that in turn consumers reject due to failing CloudEvent validation.

Of course this is preventing us from using CS as the main event gateway...

```json
{
  "id": "88c47e76-ed30-42ee-adda-4a4ca18040d2",
  "specversion": "1.0",
  "time": "2024-09-25T10:00:21.917554+00:00",
  "source": "https://dummy-source.cisco.com",
  "type": "com.cisco.certs.dummy.test.requested.v1",
  "subject": "some.interesting.concept.key_abcde12345",
  "datacontenttype": "application/json",
  "data": {
    "foo": "bar"
  },
  "sequencetype": "long",
  "sequence": 37824,
  "$traceId": "9ac45f5f402733bdb251b11024cf738a",
  "$spanId": "6e15e720f0cf8a21"
}
```

**To Reproduce**
Just stream any events from CS.

**Expected behavior**
Events streamed by CS should meed the CloudEvent' spec :)

**Comment by JBBianchi** [comment]
If I'm not mistaken, those properties are appended before the broker emits the events, probably at the gateway level when ingesting them.

**Comment by cdavernas** [comment]
@JBBianchi I dont know what gave you that impression, because I can't find it anywhere, should it be at injection or consumption time.
