### ISSUE TITLE
Searching events by any partition fails

### ISSUE THREAD

**Issue by bvandewe** [neuroglia-io/cloud-streams#64]
**Describe the bug**
Currently, the filtering using any partition (in the UI' `/events` view) doesn't work.

**To Reproduce**
Try to search for any (partitionType, partitionId) and see no resulting events.

**Comment by JBBianchi** [comment]
There is a problem with the request format.

When interacting with the UI,  a request with the following format is sent:
```
/api/core/v1/cloud-events/stream/read?direction=Backwards&partitionType=BySource&partitionId=https://mysource&offset=-1&length=26
```

With invalid `partitionType` and `partitionId` parameters, ignored by the server.
Which should be `partition.type` and `partition.id` instead.

For some reason, in the API Client, the interpolation is made to build the parameter names with a `.` but are then transformed using `.ToCamelCase()`:
[CloudStreamsCoreApiClient.CloudEvents.cs#L69](https://github.com/neuroglia-io/cloud-streams/blob/654ef2b979006af40b4fa52b06e00e4226f102a6/src/core/CloudStreams.Core.Api.Client/Services/CloudStreamsCoreApiClient.CloudEvents.cs#L69)
```csharp
//...
var queryParameters = new Dictionary<string, object>() { { $"{nameof(options.Direction)}".ToCamelCase(), options.Direction.ToString() } };
if (options.Partition != null)
{
    queryParameters.Add($"{nameof(options.Partition)}.{nameof(options.Partition.Type)}".ToCamelCase(), options.Partition.Type.ToString());
    queryParameters.Add($"{nameof(options.Partition)}.{nameof(options.Partition.Id)}".ToCamelCase(), options.Partition.Id);
}
if (options.Offset.HasValue) queryParameters.Add(nameof(options.Offset).ToCamelCase(), options.Offset.Value);
queryParameters.Add(nameof(options.Length).ToCamelCase(), options.Length);
uri += $"?{string.Join('&', queryParameters.Select(p => $"{p.Key}={p.Value}"))}";
//...
```

I think `ToCamelCase()` should be called on each part instead (even though it could probably be skipped altogether):
```csharp
  queryParameters.Add($"{nameof(options.Partition).ToCamelCase()}.{nameof(options.Partition.Type).ToCamelCase()}", options.Partition.Type.ToString());
  queryParameters.Add($"{nameof(options.Partition).ToCamelCase()}.{nameof(options.Partition.Id).ToCamelCase()}", options.Partition.Id);
```

@cdavernas wdyt ?
